### ISSUE TITLE
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!

### ISSUE THREAD

**Issue by TApplencourt** [openmole/openmole#140]
On my archlinux, i have this error when running the `openmole` script:

```
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
    at java.awt.Desktop.checkActionSupport(Desktop.java:225)
    at java.awt.Desktop.browse(Desktop.java:381)
    at org.openmole.ui.Application$$anonfun$start$1.browse$1(Application.scala:187)
    at org.openmole.ui.Application$$anonfun$start$1.apply(Application.scala:198)
    at org.openmole.ui.Application$$anonfun$start$1.apply(Application.scala:60)
    at org.openmole.core.replication.DBServerRunning$.useDB(DBServerRunning.scala:42)
    at org.openmole.ui.Application.start(Application.scala:60)
    at org.openmole.ui.Application.start(Application.scala:47)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

```

`java -version` give:

```
openjdk version "1.8.0_74"
OpenJDK Runtime Environment (build 1.8.0_74-b02)
OpenJDK 64-Bit Server VM (build 25.74-b02, mixed mode)
```

**Comment by mathieuleclaire** [comment]
Hi Thomas,
it is an error connected to the launching of your web browser (openmole
is now a client/server application). For some reason it is not possible
to launch your default browser with the java browse method. What is your
default web browser ?

However, you can launch the client anyway by surfing to the url:
https://localhost:<port>/
The <port> should have been mentionned just before the error you give.
Something like: "INFOS: Server listening on port 41278"

Mathieu
Le 01/03/2016 10:41, Thomas Applencourt a écrit :
> |java.lang.UnsupportedOperationException: The BROWSE action is not
> supported on the current platform!|


-- 
Ingénieur de Recherche ISCPIF-CNRS

Be green, keep it on the screen
Faites bonne impression et imprimez seulement au besoin!

**Comment by TApplencourt** [comment]
Hi mathieu, thx for the quick help.

Sadly i have no port =( 
```
Null identity service, trying login service: null
Finding identity service: null
!SESSION 2016-03-01 10:46:07.377 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -cp /home/razoa/Downloads/openmole/openmole-plugins -gp /home/razoa/Downloads/openmole/openmole-plugins-gui
Command-line arguments:  -consoleLog -cp /home/razoa/Downloads/openmole/openmole-plugins -gp /home/razoa/Downloads/openmole/openmole-plugins-gui

!ENTRY org.eclipse.osgi 4 0 2016-03-01 10:46:17.614
!MESSAGE Application error
!STACK 1
```

I have a modified chromium ([vivaldi](vivaldi.com)) for main browser. But, I change it to Firefox; The error persist.

**Comment by mathieuleclaire** [comment]
The fact is the browse method in java.awt.Desktop has been designed for windows and mac. It has been poorly tested on linux and only on gnome and KDE. What is your linux desktop ? Unity? That could explain why the browse method is unstable. Can you please provide with the full stack ?

**Comment by TApplencourt** [comment]
I'm using [i3](http://i3wm.org) for the windows manager. So i guess, and use nether gnone or KDE and that the problem. 

I will use the command line option of `openmol` : )

**Comment by mathieuleclaire** [comment]
This is the problem I guess. So we have to display the port number before lanching the desktop so that you could see it anyway. I will do this, and peharps you could then use openmole with the development version.

**Comment by TApplencourt** [comment]
Oh that will be nice!  Thx you

**Comment by mathieuleclaire** [comment]
Done, you can download the development version (not stable) on next.openmole.org. Then, run ./openmole --no-browser. The server will start, you will get the port so that you can run it in your browser.

**Comment by romainreuillon** [comment]
@TApplencourt may we close this issue?

**Comment by TApplencourt** [comment]
Yes for sure! Sorry for that and thanks again.
Le 12 avr. 2016 23:15, "Romain Reuillon" <notifications@github.com> a
écrit :

**Comment by guillaumecherel** [comment]
I just ran into this issue also running nixos. Would it be possible to catch the java.lang.UnsupportedOperationException when it happens, and instead of launching the browser just printing a message like "Now open your browser to the url http://localhost:..."?

Here is the full error on my case:

```
[nix-shell:~/Work/Dev/all/openmole]$ bash openmole/bin/openmole/target/assemble/openmole
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.openmole.launcher.Launcher.main(Launcher.java:147)
Caused by: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
	at org.openmole.ui.Application$.browse$1(Application.scala:256)
	at org.openmole.ui.Application$.$anonfun$run$25(Application.scala:278)
	at org.openmole.ui.Application$.$anonfun$run$25$adapted(Application.scala:274)
	at org.openmole.gui.server.core.GUIServerServices$.withServices(GUIServlet.scala:108)
	at org.openmole.ui.Application$.$anonfun$run$21(Application.scala:274)
	at org.openmole.ui.Application$.$anonfun$run$21$adapted(Application.scala:258)
	at org.openmole.tool.stream.package$.withClosable(package.scala:117)
	at org.openmole.tool.file.FilePackage$FileDecorator.$anonfun$withFileOutputStream$1(package.scala:455)
	at org.openmole.ui.Application$.run(Application.scala:258)
	at org.openmole.ui.Application.run(Application.scala)
	... 5 more
```

**Comment by guillaumecherel** [comment]
Actually, there seems to be a better way to solve it: by replacing the shebang `#!/bin/bash` by `#!/usr/bin/env bash` at the beginning of the generated executable `openmole/bin/openmole/target/assemble/openmole`, I'm not seeing the error anymore. Firefox still doesn't start, but openmole does and I do get the message "INFO: Server listening on port 34619."

**Comment by SilenceHe** [comment]
I got the same issue on WSL (Windows Subsystem for Linux) with run cmd: `allure serve -h 0.0.0.0 -p 8080 allure-result`

BTW, I used `playwright install chromium` to install chromium in WSL.
