### ISSUE TITLE
Number of reported jobs off by 1

### ISSUE THREAD

**Issue by schuhschuh** [openmole/openmole#67]
This time I think I've found a valid bug... when listening on the JobSubmitted event, the number of submitted jobs reported by the environment is not including the just submitted job. Given that the event name is in the past tense (i.e., "JobSubmitted" rather than "JobAboutToBeSubmitted"), I think this counter should already be incremented before the event is triggered.

**Comment by romainreuillon** [comment]
Agreed, I fixed it in: 29c1df5bf4f333eac9212b6613e5bb152da0857b

**Comment by romainreuillon** [comment]
and da945f8afcc1f89528d3ab3cdeab76a3c35fe57b

**Comment by schuhschuh** [comment]
Thanks, how is it about the JobCompleted event ? Will in this case the "submitted" / "running" counter already be decremented and "done" incremented ? On a side note, does the number of "submitted" jobs include the number of "running" jobs (which I think it should) ?

**Comment by schuhschuh** [comment]
Looking at the output after this fix, I can tell that the total number currently in the environment queue is the sum of "submitted" and "running", i.e., submitted jobs are those that are idle.

**Comment by schuhschuh** [comment]
Actually, regarding my second question, I've now got the answer that the numbers reported are also/still incorrect for the JobCompleted event:

```
[REPEAT 21/05/15 17:55.43] QSub: Registration for {regId=nreg2, parId=01, tgtId=1000, srcId=1001}
[REPEAT 21/05/15 17:55.43] Jobs: Local queue=long: 40 jobs; 39 idle, 1 running, 0 completed
[REPEAT 21/05/15 18:12.07] Jobs: Local queue=long: 41 jobs; 39 idle, 1 running, 1 completed
[REPEAT 21/05/15 18:12.13] Done: Registration for {regId=nreg2, parId=02, tgtId=1004, srcId=1003}
```

where I have in total 40 local jobs. After the first was finished running, the message should have read:
```
[REPEAT 21/05/15 18:12.07] Jobs: Local queue=long: 40 jobs; 39 idle, 0 running, 1 completed
```

**Comment by schuhschuh** [comment]
Besides these discrepancies in job counts using a LocalEnvironment. I am realising now that the numbers reported by OpenMOLE for other environments (such as the CondorEnvironment) are anyway far off reality. They rather reflect the state of OpenMOLE than the state of the actual environment.

```
[REPEAT 21/05/15 21:48.37] Jobs: Condor queue=long: 295 jobs; 295 idle, 0 running, 0 completed
```

vs.

condor_q
```
1665 jobs; 0 completed, 0 removed, 1446 idle, 213 running, 0 held, 6 suspended
```

I assume this has good reasons, though I would prefer the numbers to be in better agreement.

**Comment by schuhschuh** [comment]
Still somewhat surprising that the number of running jobs is even 20min later when the first job finished quite off, given that at any time more than 200 jobs are running according to condor_q:
```
[REPEAT 21/05/15 21:48.37] Jobs: Condor queue=long: 295 jobs; 295 idle, 0 running, 0 completed
[REPEAT 21/05/15 22:04.39] Jobs: Condor queue=long: 3780 jobs; 3779 idle, 0 running, 1 completed
```

**Comment by romainreuillon** [comment]
This is due to the refresh rate of job states in OpenMOLE. By default, the refresh algo is:
```
def refresh(waitTime) = {
  wait(waitTime)
  updateState
  if(statusChanged) refresh(1 min)
  else if(waitTime >= 20 min)  refresh(waitime) else refresh(waitime + 1)
}
```
For long running or waiting time the refresh rate can grow up to 20 minutes. It can be modified in the preferences.
